### ISSUE TITLE
Specify what gets deleted when you post

### ISSUE THREAD

**Issue by TheAwesome98-Real** [redtophat/wasteof2-docs#1]
I dunno how to edit wiki on the GitHub website and I’m not at my pc so I can’t `git clone`

specify on `POST /posts` that if you type something other than \<strong> \<em> \<b> \<i> \<u> \<s> \<p> \<a> \<blockquote> or \<pre>, it’s removed by both the server and the default frontend (ie. jeffalo’s)

**Comment by redtophat** [comment]
Sure thing.
