### ISSUE TITLE
Found 2 new endpoints

### ISSUE THREAD

**Issue by TheAwesome98-Real** [redtophat/wasteof2-docs#3]
It’s `GET /users/[name]/following` (who is the user following which has pages) and `GET /users/[name]/followers` (who is following the user which also has pages)

**Comment by redtophat** [comment]
These are already endpoints. You can look for yourself.

**Comment by TheAwesome98-Real** [comment]
woops didn't realise you had it already

**Comment by redtophat** [comment]
> woops didn't realise you had it already

thats fine
